[[tls.certificates]]
  certFile = "/mnt/certs/server.crt"
  keyFile = "/mnt/certs/server.key"

# Redirect http to https
#
[http.routers]
  [http.routers.http_catchall]
    entryPoints = ["web"]
    middlewares = ["https_redirect"]
    rule = "HostRegexp(`{any:.+}`)"
    service = "noop"
[http.services]
  # noop service, the URL will be never called
  [http.services.noop.loadBalancer]
    [[http.services.noop.loadBalancer.servers]]
      url = "http://192.168.0.1:1337"
[http.middlewares]
  [http.middlewares.https_redirect.redirectScheme]
    scheme = "https"
    permanent = true
